name: aew-qtrack
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas
  - scipy
  - xarray
  - netcdf4
  - matplotlib
  - cartopy
  - scikit-learn
  - joblib
  - dill
  - pytest
  - pip:
      - qtrack==0.0.4
      - gdown>=5.2
